parameters:
#    welcomebac_privee.example.class: Welcomebac\PriveeBundle\Example

services:
#    welcomebac_privee.example:
#        class: %welcomebac_privee.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
