parameters:
#    welcomebac_public.example.class: Welcomebac\PublicBundle\Example

services:
#    welcomebac_public.example:
#        class: %welcomebac_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
