security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        secured_area:
            pattern:    ^/admins/.*
            http_digest:
                key: "gaetan&remi"
            provider: in_memory

    providers:
        in_memory:
            users:
                admin: { password: kitten, roles: ROLE_USER }

